"use client";

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "./providers";
import { usePathname } from "next/navigation";
import NavbarComp from "./navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const disableNavbar = ["/login", "/register"];

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {!disableNavbar.includes(pathname) && <NavbarComp />}
          <main>{children}</main>
          <footer></footer>
        </Providers>
      </body>
    </html>
  );
}
